[package]
name = "casper-runtime"
version = "2.0.0-rc2"
authors = ["Junius Zhou"]
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
balances = { package = "pallet-balances", version = '2.0.0-rc2', default-features = false}
frame-support = { version = '2.0.0-rc2', default-features = false}
indices = { package = "pallet-indices", version = '2.0.0-rc2', default-features = false}
sudo = { package = "pallet-sudo", version = '2.0.0-rc2', default-features = false}
frame-system = { version = '2.0.0-rc2', default-features = false}
timestamp = { package = "pallet-timestamp", version = '2.0.0-rc2', default-features = false}
transaction-payment = { package = "pallet-transaction-payment", version = '2.0.0-rc2', default-features = false}
randomness-collective-flip = { package = "pallet-randomness-collective-flip", version = '2.0.0-rc2', default-features = false}

parity-scale-codec = { version = "1.3.0", default-features = false, features = ["derive"] }
frame-executive = { version = '2.0.0-rc2', default-features = false}

serde = { version = "1.0.101", optional = true, features = ["derive"] }
sp-api = { version = '2.0.0-rc2', default-features = false}
sp-block-builder = { version = '2.0.0-rc2', default-features = false}
sp-core = { version = '2.0.0-rc2', default-features = false}
sp-inherents = { version = '2.0.0-rc2', default-features = false}
sp-io = { version = '2.0.0-rc2', default-features = false}
sp-offchain = { version = '2.0.0-rc2', default-features = false}
sp-runtime = { version = '2.0.0-rc2', default-features = false}
sp-session = { version = '2.0.0-rc2', default-features = false}
sp-std = { version = '2.0.0-rc2', default-features = false}
sp-transaction-pool = { version = '2.0.0-rc2', default-features = false}
sp-version = { version = '2.0.0-rc2', default-features = false}

pallet-casper = {default-features = false, path = "../pallet"}
pallet-casper-runtime-api = {default-features = false, path = "../pallet/runtime-api"}

[build-dependencies]
wasm-builder-runner = { version = "1.0.4", package = "substrate-wasm-builder-runner" }

[features]
default = ["std"]
std = [
	"balances/std",
	"parity-scale-codec/std",
	"frame-executive/std",
	"frame-support/std",
	"frame-system/std",
	"indices/std",
	"randomness-collective-flip/std",
	"serde",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-io/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"sudo/std",
	"timestamp/std",
	"transaction-payment/std",
	"pallet-casper/std",
	"pallet-casper-runtime-api/std",
]
